"helpful insert mode abbreviations
iabbrev <buffer> -> →
iabbrev <buffer> and ∧
iabbrev <buffer> or ∨
iabbrev <buffer> not ¬
iabbrev <buffer> iff ↔
iabbrev <buffer> fun λ
iabbrev <buffer> forall ∀
iabbrev <buffer> exists ∃
